version: '3.8'

services:

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: airflow_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5438:5432
